export const SET_SELECTED_ROW_DATA = 'SET_SELECTED_ROW_DATA'
export const SET_TABLE_DATA_FROM_STORAGE = 'SET_TABLE_DATA_FROM_STORAGE'
export const ADD_ITEM_ID_TO_TREE_DATA_LIST = 'ADD_ITEM_ID_TO_TREE_DATA_LIST'
export const REMOVE_SELECTED_ROW_DATA = 'REMOVE_SELECTED_ROW_DATA'
